V_COPY (select
g.id as game_id,
g.season,
g.week,
g.start_date,
gthome.team_id as HomeID,
gtaway.team_id as VisID,
gthome.school as Home_School,
gthome.ncaa_name as Home_NCAA_Name,
gthome.alt_name as Home_Alt_Name,
gthome.nickname as Home_Nickname,
gthome.abbreviation as Home_Abbreviation,
gthome.display_name as Home_Display_Name,
gthome.short_display_name as Home_Short_Display_Name,
gtaway.school as Visiter_School,
gtaway.ncaa_name as Visiter_NCAA_Name,
gtaway.alt_name as Visiter_Alt_Name,
gtaway.nickname as Visiter_Nickname,
gtaway.abbreviation as Visiter_Abbreviation,
gtaway.display_name as Visiter_Display_Name,
gtaway.short_display_name as Visiter_Short_Display_Name,
g.conference_game,
gthome.points as HomeFinal,
gtaway.points as VisFinal,

-- sum(case when d.offense_id = gthome.team_id then d.elapsed else 0 end) as H_OffenseTime,
avg(case when d.offense_id = gthome.team_id then d.start_yardline else null end) as H_AvgStartYard,
avg(case when d.offense_id = gthome.team_id then d.end_yardline else null end) as H_AvgEndYard,
sum(case when d.offense_id = gthome.team_id then d.yards else 0 end) as H_YardsGained,
sum(case when d.offense_id = gthome.team_id then d.plays else 0 end) as H_PlayCount,
sum(case when d.defense_id = gthome.team_id and d.result_id = 1 then 1 else 0 end) as H_BLOCKED_PUNT_TD_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 2 then 1 else 0 end) as H_FG_GOOD_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 3 then 1 else 0 end) as H_LATERAL,
sum(case when d.defense_id = gthome.team_id and d.result_id = 4 then 1 else 0 end) as H_FUMBLE_RETURN_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 5 then 1 else 0 end) as H_TURNOVER_ON_DOWNS,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 6 then 1 else 0 end) as H_SF,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 7 then 1 else 0 end) as H_NETRCV,
sum(case when d.offense_id = gthome.team_id and d.result_id = 8 then 1 else 0 end) as H_TURNOVER_ON_DOWNS_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 9 then 1 else 0 end) as H_BLOCKED_FG,
sum(case when d.defense_id = gthome.team_id and d.result_id = 10 then 1 else 0 end) as H_INT_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 11 then 1 else 0 end) as H_RUSH,
sum(case when d.offense_id = gthome.team_id and d.result_id = 12 then 1 else 0 end) as H_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 13 then 1 else 0 end) as H_RUSHING_TD_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 14 then 1 else 0 end) as H_BLOCKED_FG_TD_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 15 then 1 else 0 end) as H_PUNT_RETURN_TD,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 16 then 1 else 0 end) as H_END_OF_HALF,
sum(case when d.offense_id = gthome.team_id and d.result_id = 17 then 1 else 0 end) as H_PASSING_TD_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 18 then 1 else 0 end) as H_MISSED_FG_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 19 then 1 else 0 end) as H_PASS_COMPLETE,
sum(case when d.offense_id = gthome.team_id and d.result_id = 20 then 1 else 0 end) as H_END_OF_GAME_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 21 then 1 else 0 end) as H_MADE_FG,
sum(case when d.offense_id = gthome.team_id and d.result_id = 22 then 1 else 0 end) as H_FG_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 23 then 1 else 0 end) as H_MISSED_PAT_RETURN,
sum(case when d.offense_id = gthome.team_id and d.result_id = 24 then 1 else 0 end) as H_DOWNS_TD,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 25 then 1 else 0 end) as H_END_OF_GAME,
sum(case when d.offense_id = gthome.team_id and d.result_id = 26 then 1 else 0 end) as H_END_OF_HALF_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 27 then 1 else 0 end) as H_OINT,
sum(case when d.defense_id = gthome.team_id and d.result_id = 27 then 1 else 0 end) as H_DINT,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 28 then 1 else 0 end) as H_KICKOFF,
sum(case when d.offense_id = gthome.team_id and d.result_id = 29 then 1 else 0 end) as H_MISSED_FG,
sum(case when d.offense_id = gthome.team_id and d.result_id = 30 then 1 else 0 end) as H_FG,
sum(case when d.offense_id = gthome.team_id and d.result_id = 31 then 1 else 0 end) as H_LATERAL_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 32 then 1 else 0 end) as H_BLOCKED_PUNT,
sum(case when d.offense_id = gthome.team_id and d.result_id = 33 then 1 else 0 end) as H_POSS_ON_DOWNS,
sum(case when d.offense_id = gthome.team_id and d.result_id = 34 then 1 else 0 end) as H_INCOMPLETE,
sum(case when d.defense_id = gthome.team_id and d.result_id = 35 then 1 else 0 end) as H_BLOCKED_PUNT_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 36 then 1 else 0 end) as H_SACK,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 37 then 1 else 0 end) as H_TIMEOUT,
sum(case when d.offense_id = gthome.team_id and d.result_id = 38 then 1 else 0 end) as H_FG_MISSED_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 39 then 1 else 0 end) as H_OTWOPT_PASS_FAILED,
sum(case when d.defense_id = gthome.team_id and d.result_id = 39 then 1 else 0 end) as H_DTWOPT_PASS_FAILED,
sum(case when d.offense_id = gthome.team_id and d.result_id = 40 then 1 else 0 end) as H_INT_RETURN_TOUCH,
sum(case when d.offense_id = gthome.team_id and d.result_id = 41 then 1 else 0 end) as H_POSSESSION_FOR_OT_DRIVES,
sum(case when d.defense_id = gthome.team_id and d.result_id = 42 then 1 else 0 end) as H_PUNT_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 43 then 1 else 0 end) as H_KICK_RETURN_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 44 then 1 else 0 end) as H_KICKOFF_RETURN_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 45 then 1 else 0 end) as H_MISSED_FG_TD_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 46 then 1 else 0 end) as H_OFUMBLE_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 46 then 1 else 0 end) as H_DFUMBLE_TD,
sum(case when d.defense_id = gthome.team_id and d.result_id = 47 then 1 else 0 end) as H_BLOCKED_FG_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 48 then 1 else 0 end) as H_PUNT,
sum(case when d.offense_id = gthome.team_id and d.result_id = 49 then 1 else 0 end) as H_PASSING_TD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 50 then 1 else 0 end) as H_OPENALTY,
sum(case when d.defense_id = gthome.team_id and d.result_id = 50 then 1 else 0 end) as H_DPENALTY,
sum(case when d.offense_id = gthome.team_id and d.result_id = 51 then 1 else 0 end) as H_FG_GOOD,
sum(case when d.offense_id = gthome.team_id and d.result_id = 52 then 1 else 0 end) as H_FUMBLE,
sum(case when d.offense_id = gthome.team_id and d.result_id = 53 then 1 else 0 end) as H_FG_MISSED,
sum(case when d.defense_id = gthome.team_id and d.result_id = 54 then 1 else 0 end) as H_PUNT_RETURN_TD_TD,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 55 then 1 else 0 end) as H_DOWNS,
sum(case when d.offense_id = gthome.team_id and d.result_id = 56 then 1 else 0 end) as H_RUSHING_TD,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 57 then 1 else 0 end) as H_POSSESSION_FOR_OT_DRIVES_TD,
-- sum(case when d.offense_id = gthome.team_id and d.result_id = 58 then 1 else 0 end) as H_Uncategorized,
sum(case when p.offense_id = gthome.team_id then p.SUM_FIRSTDOWN_DISTANCE else 0 end) as H_TOT_FIRSTDOWN_DISTANCE,
sum(case when p.offense_id = gthome.team_id then p.SUM_SECONDDOWN_DISTANCE else 0 end) as H_TOT_SECONDDOWN_DISTANCE,
sum(case when p.offense_id = gthome.team_id then p.SUM_THIRDDOWN_DISTANCE else 0 end) as H_TOT_THIRDDOWN_DISTANCE,
sum(case when p.offense_id = gthome.team_id then p.SUM_FOURTHDOWN_DISTANCE else 0 end) as H_TOT_FOURTHDOWN_DISTANCE,
sum(case when p.offense_id = gthome.team_id then p.SUM_DISTANCE else 0 end) as H_TOT_DISTANCE,
sum(case when p.offense_id = gthome.team_id then p.SUM_FIRSTDOWN_YARDSGAINED else 0 end) as H_TOT_FIRSTDOWN_YARDSGAINED,
sum(case when p.offense_id = gthome.team_id then p.SUM_SECONDDOWN_YARDSGAINED else 0 end) as H_TOT_SECONDDOWN_YARDSGAINED,
sum(case when p.offense_id = gthome.team_id then p.SUM_THIRDDOWN_YARDSGAINED else 0 end) as H_TOT_THIRDDOWN_YARDSGAINED,
sum(case when p.offense_id = gthome.team_id then p.SUM_FOURTHDOWN_YARDSGAINED else 0 end) as H_TOT_FOURTHDOWN_YARDSGAINED,
sum(case when p.offense_id = gthome.team_id then p.SUM_YARDSGAINED else 0 end) as H_TOT_YARDSGAINED,
sum(case when p.offense_id = gthome.team_id then p.COUNT_FIRSTDOWNS else 0 end) as H_COUNT_FIRSTDOWNS,
sum(case when p.offense_id = gthome.team_id then p.COUNT_SECONDDOWNS else 0 end) as H_COUNT_SECONDDOWNS,
sum(case when p.offense_id = gthome.team_id then p.COUNT_THIRDDOWNS else 0 end) as H_COUNT_THIRDDOWNS,
sum(case when p.offense_id = gthome.team_id then p.COUNT_FOURTHDOWNS else 0 end) as H_COUNT_FOURTHDOWNS,


-- sum(case when d.offense_id = gtaway.team_id then d.elapsed else 0 end) as V_OffenseTime,
avg(case when d.offense_id = gtaway.team_id then d.start_yardline else null end) as V_AvgStartYard,
avg(case when d.offense_id = gtaway.team_id then d.end_yardline else null end) as V_AvgEndYard,
sum(case when d.offense_id = gtaway.team_id then d.yards else 0 end) as V_YardsGained,
sum(case when d.offense_id = gtaway.team_id then d.plays else 0 end) as V_PlayCount,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 1 then 1 else 0 end) as V_BLOCKED_PUNT_TD_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 2 then 1 else 0 end) as V_FG_GOOD_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 3 then 1 else 0 end) as V_LATERAL,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 4 then 1 else 0 end) as V_FUMBLE_RETURN_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 5 then 1 else 0 end) as V_TURNOVER_ON_DOWNS,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 6 then 1 else 0 end) as V_SF,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 7 then 1 else 0 end) as V_NETRCV,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 8 then 1 else 0 end) as V_TURNOVER_ON_DOWNS_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 9 then 1 else 0 end) as V_BLOCKED_FG,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 10 then 1 else 0 end) as V_INT_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 11 then 1 else 0 end) as V_RUSH,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 12 then 1 else 0 end) as V_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 13 then 1 else 0 end) as V_RUSHING_TD_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 14 then 1 else 0 end) as V_BLOCKED_FG_TD_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 15 then 1 else 0 end) as V_PUNT_RETURN_TD,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 16 then 1 else 0 end) as V_END_OF_HALF,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 17 then 1 else 0 end) as V_PASSING_TD_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 18 then 1 else 0 end) as V_MISSED_FG_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 19 then 1 else 0 end) as V_PASS_COMPLETE,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 20 then 1 else 0 end) as V_END_OF_GAME_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 21 then 1 else 0 end) as V_MADE_FG,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 22 then 1 else 0 end) as V_FG_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 23 then 1 else 0 end) as V_MISSED_PAT_RETURN,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 24 then 1 else 0 end) as V_DOWNS_TD,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 25 then 1 else 0 end) as V_END_OF_GAME,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 26 then 1 else 0 end) as V_END_OF_HALF_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 27 then 1 else 0 end) as V_OINT,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 27 then 1 else 0 end) as V_DINT,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 28 then 1 else 0 end) as V_KICKOFF,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 29 then 1 else 0 end) as V_MISSED_FG,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 30 then 1 else 0 end) as V_FG,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 31 then 1 else 0 end) as V_LATERAL_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 32 then 1 else 0 end) as V_BLOCKED_PUNT,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 33 then 1 else 0 end) as V_POSS_ON_DOWNS,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 34 then 1 else 0 end) as V_INCOMPLETE,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 35 then 1 else 0 end) as V_BLOCKED_PUNT_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 36 then 1 else 0 end) as V_SACK,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 37 then 1 else 0 end) as V_TIMEOUT,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 38 then 1 else 0 end) as V_FG_MISSED_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 39 then 1 else 0 end) as V_OTWOPT_PASS_FAILED,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 39 then 1 else 0 end) as V_DTWOPT_PASS_FAILED,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 40 then 1 else 0 end) as V_INT_RETURN_TOUCH,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 41 then 1 else 0 end) as V_POSSESSION_FOR_OT_DRIVES,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 42 then 1 else 0 end) as V_PUNT_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 43 then 1 else 0 end) as V_KICK_RETURN_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 44 then 1 else 0 end) as V_KICKOFF_RETURN_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 45 then 1 else 0 end) as V_MISSED_FG_TD_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 46 then 1 else 0 end) as V_OFUMBLE_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 46 then 1 else 0 end) as V_DFUMBLE_TD,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 47 then 1 else 0 end) as V_BLOCKED_FG_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 48 then 1 else 0 end) as V_PUNT,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 49 then 1 else 0 end) as V_PASSING_TD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 50 then 1 else 0 end) as V_OPENALTY,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 50 then 1 else 0 end) as V_DPENALTY,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 51 then 1 else 0 end) as V_FG_GOOD,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 52 then 1 else 0 end) as V_FUMBLE,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 53 then 1 else 0 end) as V_FG_MISSED,
sum(case when d.defense_id = gtaway.team_id and d.result_id = 54 then 1 else 0 end) as V_PUNT_RETURN_TD_TD,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 55 then 1 else 0 end) as V_DOWNS,
sum(case when d.offense_id = gtaway.team_id and d.result_id = 56 then 1 else 0 end) as V_RUSHING_TD,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 57 then 1 else 0 end) as V_POSSESSION_FOR_OT_DRIVES_TD,
-- sum(case when d.offense_id = gtaway.team_id and d.result_id = 58 then 1 else 0 end) as V_Uncategorized,
sum(case when p.offense_id = gtaway.team_id then p.SUM_FIRSTDOWN_DISTANCE else 0 end) as V_TOT_FIRSTDOWN_DISTANCE,
sum(case when p.offense_id = gtaway.team_id then p.SUM_SECONDDOWN_DISTANCE else 0 end) as V_TOT_SECONDDOWN_DISTANCE,
sum(case when p.offense_id = gtaway.team_id then p.SUM_THIRDDOWN_DISTANCE else 0 end) as V_TOT_THIRDDOWN_DISTANCE,
sum(case when p.offense_id = gtaway.team_id then p.SUM_FOURTHDOWN_DISTANCE else 0 end) as V_TOT_FOURTHDOWN_DISTANCE,
sum(case when p.offense_id = gtaway.team_id then p.SUM_DISTANCE else 0 end) as V_TOT_DISTANCE,
sum(case when p.offense_id = gtaway.team_id then p.SUM_FIRSTDOWN_YARDSGAINED else 0 end) as V_TOT_FIRSTDOWN_YARDSGAINED,
sum(case when p.offense_id = gtaway.team_id then p.SUM_SECONDDOWN_YARDSGAINED else 0 end) as V_TOT_SECONDDOWN_YARDSGAINED,
sum(case when p.offense_id = gtaway.team_id then p.SUM_THIRDDOWN_YARDSGAINED else 0 end) as V_TOT_THIRDDOWN_YARDSGAINED,
sum(case when p.offense_id = gtaway.team_id then p.SUM_FOURTHDOWN_YARDSGAINED else 0 end) as V_TOT_FOURTHDOWN_YARDSGAINED,
sum(case when p.offense_id = gtaway.team_id then p.SUM_YARDSGAINED else 0 end) as V_TOT_YARDSGAINED,
sum(case when p.offense_id = gtaway.team_id then p.COUNT_FIRSTDOWNS else 0 end) as V_COUNT_FIRSTDOWNS,
sum(case when p.offense_id = gtaway.team_id then p.COUNT_SECONDDOWNS else 0 end) as V_COUNT_SECONDDOWNS,
sum(case when p.offense_id = gtaway.team_id then p.COUNT_THIRDDOWNS else 0 end) as V_COUNT_THIRDDOWNS,
sum(case when p.offense_id = gtaway.team_id then p.COUNT_FOURTHDOWNS else 0 end) as V_COUNT_FOURTHDOWNS

from
game g
left join (select
           game_id,
           team_id,
           t.school,
           t.ncaa_name,
           t.alt_name,
           t.nickname,
           t.abbreviation,
           t.display_name,
           t.short_display_name,
           points
           from
           game_team g
           left join team t on g.team_id = t.id
           where
           home_away = 'home') as gthome on g.id = gthome.game_id
left join (select
           game_id,
           team_id,
           t.school,
           t.ncaa_name,
           t.alt_name,
           t.nickname,
           t.abbreviation,
           t.display_name,
           t.short_display_name,
           points
           from
           game_team g
           left join team t on g.team_id = t.id
           where
           home_away = 'away') as gtaway on g.id = gtaway.game_id
left join drive d on g.id = d.game_id
left join (select
           drive_id,
           offense_id,
           sum(case when down = 1 then distance else 0 end) as SUM_FIRSTDOWN_DISTANCE,
           sum(case when down = 2 then distance else 0 end) as SUM_SECONDDOWN_DISTANCE,
           sum(case when down = 3 then distance else 0 end) as SUM_THIRDDOWN_DISTANCE,
           sum(case when down = 4 then distance else 0 end) as SUM_FOURTHDOWN_DISTANCE,
           sum(distance) as SUM_DISTANCE,
           sum(case when down = 1 then yards_gained else 0 end) as SUM_FIRSTDOWN_YARDSGAINED,
           sum(case when down = 2 then yards_gained else 0 end) as SUM_SECONDDOWN_YARDSGAINED,
           sum(case when down = 3 then yards_gained else 0 end) as SUM_THIRDDOWN_YARDSGAINED,
           sum(case when down = 4 then yards_gained else 0 end) as SUM_FOURTHDOWN_YARDSGAINED,
           sum(yards_gained) as SUM_YARDSGAINED,
           sum(case when down = 1 then 1 else 0 end) as COUNT_FIRSTDOWNS,
           sum(case when down = 2 then 1 else 0 end) as COUNT_SECONDDOWNS,
           sum(case when down = 3 then 1 else 0 end) as COUNT_THIRDDOWNS,
           sum(case when down = 4 then 1 else 0 end) as COUNT_FOURTHDOWNS
           from
           play
           group by
           1,2) as p on d.id = p.drive_id


group by
1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23) TO '/Users/stephencarrow/Documents/DS-GA 1003 Machine Learning/Project/NYUMLProject/data/ultimate_cfb_dataset.csv' (format csv, header, delimiter ',')
;
